language: node_js
node_js:
- '0.12'
env:
  global:
  - GH_REF=github.com/openaq/openaq-api.git
  - PRODUCTION_BRANCH=master
  - secure: 113kZJZVCdp/5MI65f/RNgR6xYux1e5py8ceJ8LPPvP6sZz3NpCNxaWegQyum0xQpwEcEITw1yFl8bDnY0sPdKsIIOrl7SCdiigW8lh2VjS8R5U9xpHj/pbEYlxgn3dLNorrV4gyFMTQjQHT+Hy07d4m5AVdtRK1y+xX1ztr+HOWM0cp1Iio+8myohnB5FaTDvAbXqzn/TCkjnC7H+fVk0MVWSCf57EGsjiCkt+iUYOUhC3H+IykOYP1vDLOwpKdWysVq7cj1LtyPf9FqA5gJiEfh5uDxxoSdSayWJytvqquqru5Rz01yQdGrF76HOoUqZUZt37TLd8KhK0gXcIRjCUNKbX75TEfMvUE7usgOmkp9XtTSHyy603oZkv7MASj7XjdseGeBJuLZKrSwXZXZPJi27Gziew6KBu0hxIVIB6nr549DhWD0n3jYKeB8dKXMm7Irl2EbavBxDM+2NlRVEy9MTPcJndD7+JGohbTXCui+G+oHononq3CPfazvEA6P9S550+EaZ3Op1WhhTf2HlvOXgVP/f0TAVPmAlq/+snJeQKEHTh9E85s3UoJWrDxJ1BBGQfyB1fDM+ksoOvo3aAkubvYFpIVYOMnsep+SeYut4DJc4tfz11N06usqi9sRPO1taGQStVO2Ptoq5GYo9YYJjvaQ5bw7Q9NGLzDsfA=
branches:
  only:
  - master
before_install:
- chmod +x ./.build_scripts/docs.sh
after_success:
- "./.build_scripts/docs.sh"
deploy:
  provider: heroku
  api_key:
    secure: E0Hyt+HMDb0NYR8fySMn2kYja+AkZccKakFuOPYVHyb791+YZYSq0+8QxIQ8ktIibsP+YxB941lgB1LDyDpNLLywzt5zDi+i5pwCfB8QwDdx2InUhkxC1HY+s0KKQwVq5nF9iLxWZ0L2wV3QPc1LS3togE5kq2Q/GWrJefhJ1IIn+BMn7HVuNe4iLhwVxp2+HLQmdE+ibqjB0YvavjQlLD64ItAkeS5ROgc4UQjzMWcDUiyfDr6qLsE+jXEfq7muhmb9KQ7rNUjRW/P7eh/jRNH0bZYZ06BaIkYyAkEv946bHZebnFeEgS7d/rk6uLtWegF+vA3Iv/5wKBFoL2Gp7tf7/TNMYIsUC7IGBiWf8TZtH0SJGrBGH5E98zJrLsVAiTmePhDEpg0Q39XZQo0vT92VKSiDHX07r7PBu5hnJiw8nAmJPJkDu9vfj9tlQmhbkvWd/Omkup16SOdoXa8+X0EcDxReWwgIHChY/NAckOjmWpJzoCZrYlv7Beh7WFZMzOskjQ7FYSNpt/GSOC9rrGTwVfNg8kVOhRKYONZoKC9layiQrKXYtEWBdDfPhN1xG/ldKT0/2XRpsSD0e5/sYgzMmNd9sZFu9h/PaFqXMJQSR0gHp32PJbMxjcpuS7GdJYVSZSuVnJdAv6nikXH+uz5UZT5/ZuzHtUdfxSDCg18=
  app: nameless-ocean-6420
  on:
    repo: openaq/openaq-api
