language: node_js

node_js:
- '0.12'

env:
  global:
  - GH_REF=github.com/openaq/openaq-api.git
  - PRODUCTION_BRANCH=master
  - secure: 113kZJZVCdp/5MI65f/RNgR6xYux1e5py8ceJ8LPPvP6sZz3NpCNxaWegQyum0xQpwEcEITw1yFl8bDnY0sPdKsIIOrl7SCdiigW8lh2VjS8R5U9xpHj/pbEYlxgn3dLNorrV4gyFMTQjQHT+Hy07d4m5AVdtRK1y+xX1ztr+HOWM0cp1Iio+8myohnB5FaTDvAbXqzn/TCkjnC7H+fVk0MVWSCf57EGsjiCkt+iUYOUhC3H+IykOYP1vDLOwpKdWysVq7cj1LtyPf9FqA5gJiEfh5uDxxoSdSayWJytvqquqru5Rz01yQdGrF76HOoUqZUZt37TLd8KhK0gXcIRjCUNKbX75TEfMvUE7usgOmkp9XtTSHyy603oZkv7MASj7XjdseGeBJuLZKrSwXZXZPJi27Gziew6KBu0hxIVIB6nr549DhWD0n3jYKeB8dKXMm7Irl2EbavBxDM+2NlRVEy9MTPcJndD7+JGohbTXCui+G+oHononq3CPfazvEA6P9S550+EaZ3Op1WhhTf2HlvOXgVP/f0TAVPmAlq/+snJeQKEHTh9E85s3UoJWrDxJ1BBGQfyB1fDM+ksoOvo3aAkubvYFpIVYOMnsep+SeYut4DJc4tfz11N06usqi9sRPO1taGQStVO2Ptoq5GYo9YYJjvaQ5bw7Q9NGLzDsfA=

branches:
  only:
  - master

before_install:
- chmod +x ./.build_scripts/docs.sh

after_success:
- ./.build_scripts/docs.sh

deploy:
  provider: heroku
  api_key:
    secure: smC4UUJdYf7nl2yKp7tRusKewxF+oKmGAYAjIm3754CvnkDEr2gQ6NsqJUZb7Aadiw4q/84KGT9yswo/iFmKVb5dbuFROu8e2iH0hDaUs9eOCK5WEHdba8khwl1iAt0+UWRu4jx05Ddo8VNpZ+PJqmS/TP2mafIZqymcQJSajQXdqFobdUv0ZRZn7Apw4AilLM5itSbX1gtP6ZFDJnFDtnK5lKOCfNUoUWVJ5sUP7vwIBWfrRkRotVKHRQyEia4lSb6ocB02Jfb7oaLQ7c8AqKCd5cTkrshESvW0B70pdy2YN/wdhHZdXB1fST29dYkbjzfu37moAC7f4Ky6LHzoLj6SM24I2tiF0PPNtWk9tgGswdv5OWplgg6yYXbbCZ0SYq+4lN08+D5MP22thkQehok7Qm9cWFUOjFl9Ev6xmx8477Ptmlyqt/Wa5vHZlZX+sSa2EzGf+VbFEvNv1wsYM0fsLnbyxOjRPVJB0Pyr7x1nwxpggedUe1sWsQYgAkRH0GbMfeEqlBKzjJ02CIBURs74YLPLXvp83FwLUwjMqOTbmuS2x9oMhoWSh7F3R4OoSscT1eerhb662fj2niYZCoYn0NsdF/COMarn8ut/If63bW5YUXuXR9A0kQm6gXfbmy1+ppQWCjDDblJ6jHGGyzNsZDy4x1W48/utoxZRxjA=
  app: nameless-ocean-6420
  on:
    repo: openaq/openaq-api
